"""empty message

Revision ID: f9b8836512a4
Revises: 1fdf097127ff
Create Date: 2021-09-15 21:05:26.994963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b8836512a4'
down_revision = '1fdf097127ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
